(begin
  ("Scala"
   "AssignmentExpression"
   #\nul
   V-a
   (("Scala"
     "PostfixExpression"
     ("Scala"
      "InfixExpression"
      ("Scala"
       "PrefixExpression"
       #\nul
       ("Scala"
        "SimpleExpression"
        ("Scala"
         "TupleExpression"
         ("Scala"
          "Exprs"
          (("Scala"
            "AnonymousFunction"
            (lambda (V-x\x60;29* V-y\x60;29*)
              ("Scala"
               "PostfixExpression"
               ("Scala"
                "InfixExpression"
                ("Scala"
                 "PrefixExpression"
                 #\nul
                 ("Scala"
                  "SimpleExpression"
                  ("Scala"
                   "idSeqSimpleExpression"
                   ("Scala"
                    "PostfixExpression"
                    ("Scala"
                     "InfixExpression"
                     ("Scala"
                      "PrefixExpression"
                      #\nul
                      ("Scala"
                       "SimpleExpression"
                       ("Scala" "idSeqSimpleExpression" V-x\x60;29*)
                       #\nul))
                     (("Scala" "Identifier" "*"))
                     (("Scala"
                       "InfixExpression"
                       ("Scala"
                        "PrefixExpression"
                        #\nul
                        ("Scala"
                         "SimpleExpression"
                         ("Scala" "idSeqSimpleExpression" V-y\x60;29*)
                         #\nul)))))
                    #\nul))
                  #\nul)))
               #\nul)))))
         ("Scala"
          "FunctionApplicationPostfix"
          ("Scala"
           "ArgumentExpression"
           ("Scala"
            "Exprs"
            (("Scala"
              "PostfixExpression"
              ("Scala"
               "InfixExpression"
               ("Scala"
                "PrefixExpression"
                #\nul
                ("Scala"
                 "SimpleExpression"
                 ("Scala"
                  "idSeqSimpleExpression"
                  ("Scala"
                   "PostfixExpression"
                   ("Scala"
                    "InfixExpression"
                    ("Scala"
                     "PrefixExpression"
                     #\nul
                     ("Scala" "SimpleExpression" ("Scala" "literalSimpleExpression" 3) #\nul)))
                   #\nul))
                 #\nul)))
              #\nul)
             ("Scala"
              "PostfixExpression"
              ("Scala"
               "InfixExpression"
               ("Scala"
                "PrefixExpression"
                #\nul
                ("Scala"
                 "SimpleExpression"
                 ("Scala"
                  "idSeqSimpleExpression"
                  ("Scala"
                   "PostfixExpression"
                   ("Scala"
                    "InfixExpression"
                    ("Scala"
                     "PrefixExpression"
                     #\nul
                     ("Scala" "SimpleExpression" ("Scala" "literalSimpleExpression" 10) #\nul)))
                   #\nul))
                 #\nul)))
              #\nul))))))
        #\nul)))
     #\nul))))