(begin
  ("Scala"
   "AssignmentExpression"
   #\nul
   V-a
   ("Scala"
    "PostfixExpression"
    ("Scala"
     "InfixExpression"
     ("Scala"
      "PrefixExpression"
      #\nul
      ("Scala" "SimpleExpression" ("Scala" "idSeqSimpleExpression" V-false) #\nul)))
    #\nul))
  ("Scala"
   "AssignmentExpression"
   #\nul
   V-f
   ("Scala"
    "PostfixExpression"
    ("Scala"
     "InfixExpression"
     ("Scala"
      "PrefixExpression"
      ("Scala" "Keyword" "-")
      ("Scala" "SimpleExpression" ("Scala" "literalSimpleExpression" 1) #\nul)))
    #\nul))
  ("Scala"
   "AssignmentExpression"
   #\nul
   V-a
   (("Scala"
     "PostfixExpression"
     ("Scala"
      "InfixExpression"
      ("Scala"
       "PrefixExpression"
       #\nul
       ("Scala"
        "SimpleExpression"
        ("Scala"
         "TupleExpression"
         ("Scala"
          "Exprs"
          (("Scala"
            "AnonymousFunction"
            (lambda (V-f\x60;28\x60;29*)
              ("Scala"
               "PostfixExpression"
               ("Scala"
                "InfixExpression"
                ("Scala"
                 "PrefixExpression"
                 #\nul
                 ("Scala"
                  "BlockExpression"
                  ("Scala"
                   "Block"
                   (("Scala"
                     "IfStatement"
                     ("Scala"
                      "PostfixExpression"
                      ("Scala"
                       "InfixExpression"
                       ("Scala"
                        "PrefixExpression"
                        #\nul
                        ("Scala"
                         "SimpleExpression"
                         ("Scala" "idSeqSimpleExpression" V-f\x60;28\x60;29*)
                         #\nul)))
                      #\nul)
                     ("Scala"
                      "PostfixExpression"
                      ("Scala"
                       "InfixExpression"
                       ("Scala"
                        "PrefixExpression"
                        #\nul
                        ("Scala"
                         "SimpleExpression"
                         ("Scala" "idSeqSimpleExpression" V-f\x60;28\x60;29*)
                         #\nul)))
                      #\nul)
                     ("Scala"
                      "PostfixExpression"
                      ("Scala"
                       "InfixExpression"
                       ("Scala"
                        "PrefixExpression"
                        #\nul
                        ("Scala" "SimpleExpression" ("Scala" "idSeqSimpleExpression" V-f) #\nul)))
                      #\nul)))
                   #\nul))))
               #\nul)))))
         ("Scala"
          "FunctionApplicationPostfix"
          ("Scala"
           "ArgumentExpression"
           ("Scala"
            "Exprs"
            (("Scala"
              "PostfixExpression"
              ("Scala"
               "InfixExpression"
               ("Scala"
                "PrefixExpression"
                #\nul
                ("Scala"
                 "SimpleExpression"
                 ("Scala"
                  "idSeqSimpleExpression"
                  ("Scala"
                   "PostfixExpression"
                   ("Scala"
                    "InfixExpression"
                    ("Scala"
                     "PrefixExpression"
                     #\nul
                     ("Scala" "SimpleExpression" ("Scala" "idSeqSimpleExpression" V-false) #\nul)))
                   #\nul))
                 #\nul)))
              #\nul))))))
        #\nul)))
     #\nul))))