(begin
  ("Scala"
   "TopStat"
   #\nul
   #\nul
   ("Scala"
    "ObjectTemplateDefinition"
    #\nul
    ("Scala"
     "ObjectDefinition"
     V-Append1
     ("Scala"
      "ClassTemplateOpt"
      #\nul
      ("Scala"
       "TemplateBody"
       (letrec* ((V-ta\x60;28* ((type TypeDeclaration) (#\nul #\nul #\nul) #\nul (#\nul #\nul)))
                 (V-tb\x60;28*
                   ((type TypeDeclaration)
                    (#\nul #\nul #\nul)
                    #\nul
                    (#\nul (("Scala" "AccessModifier" ("Scala" "Keyword" "private ") #\nul)))))
                 (V-t\x60;28*
                   ((val variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (R-Int-)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    #\nul
                    (#\nul #\nul)))
                 (V-g\x60;28*
                   ((val variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (R-Int-)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    #\nul
                    (#\nul (("Scala" "AccessModifier" ("Scala" "Keyword" "private ") #\nul)))))
                 (V-w\x60;28*
                   ((var variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (R-Int-)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    #\nul
                    (#\nul #\nul)))
                 (V-q\x60;28*
                   ((var variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (R-Int-)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    #\nul
                    (#\nul (("Scala" "AccessModifier" ("Scala" "Keyword" "private ") #\nul)))))
                 (V-c\x60;28*
                   ((val variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (R-Int-)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    ("Scala"
                     "PostfixExpression"
                     ("Scala"
                      "InfixExpression"
                      ("Scala"
                       "PrefixExpression"
                       #\nul
                       ("Scala"
                        "SimpleExpression"
                        ("Scala" "literalSimpleExpression" 10 #\nul)
                        #\nul))
                      #\nul
                      #\nul)
                     #\nul)
                    (#\nul #\nul)))
                 (V-a\x60;28*
                   ((val variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (R-Int-)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    ("Scala"
                     "PostfixExpression"
                     ("Scala"
                      "InfixExpression"
                      ("Scala"
                       "PrefixExpression"
                       #\nul
                       ("Scala"
                        "SimpleExpression"
                        ("Scala" "literalSimpleExpression" 3 #\nul)
                        #\nul))
                      #\nul
                      #\nul)
                     #\nul)
                    (#\nul (("Scala" "AccessModifier" ("Scala" "Keyword" "private ") #\nul)))))
                 (V-d\x60;28*
                   ((var variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (R-Int-)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    ("Scala"
                     "PostfixExpression"
                     ("Scala"
                      "InfixExpression"
                      ("Scala"
                       "PrefixExpression"
                       #\nul
                       ("Scala"
                        "SimpleExpression"
                        ("Scala" "literalSimpleExpression" 10 #\nul)
                        #\nul))
                      #\nul
                      #\nul)
                     #\nul)
                    (#\nul #\nul)))
                 (V-b\x60;28*
                   ((var variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (R-Int-)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    ("Scala"
                     "PostfixExpression"
                     ("Scala"
                      "InfixExpression"
                      ("Scala"
                       "PrefixExpression"
                       #\nul
                       ("Scala"
                        "SimpleExpression"
                        ("Scala" "literalSimpleExpression" 10 #\nul)
                        #\nul))
                      #\nul
                      #\nul)
                     #\nul)
                    (#\nul (("Scala" "AccessModifier" ("Scala" "Keyword" "private ") #\nul)))))
                 (V-doIt\x60;28*
                   ((lambda (V-doIt\x60;29*)
                      (function Procedure)
                      (#\nul (("Scala" "Keyword" "lazy ")))
                      ("Scala"
                       "FunctionSignature"
                       V-doIt\x60;29*
                       #\nul
                       ("Scala" "ParamClauses" (("Scala" "ParamClause" #\nul)) #\nul))
                      #\nul
                      ("Scala"
                       "Block"
                       (let ()
                         (("Scala"
                           "PostfixExpression"
                           ("Scala"
                            "InfixExpression"
                            ("Scala"
                             "PrefixExpression"
                             #\nul
                             ("Scala"
                              "SimpleExpression"
                              ("Scala"
                               "idSeqSimpleExpression"
                               V-println
                               ("Scala"
                                "FunctionApplicationPostfix"
                                ("Scala"
                                 "ArgumentExpression"
                                 ("Scala"
                                  "Exprs"
                                  (("Scala"
                                    "PostfixExpression"
                                    ("Scala"
                                     "InfixExpression"
                                     ("Scala"
                                      "PrefixExpression"
                                      #\nul
                                      ("Scala"
                                       "SimpleExpression"
                                       ("Scala" "literalSimpleExpression" 3 #\nul)
                                       #\nul))
                                     #\nul
                                     #\nul)
                                    #\nul))))
                                #\nul))
                              #\nul))
                            #\nul
                            #\nul)
                           #\nul))
                         #\nul)))))
                 (R-main-\x60;28*
                   ((lambda (R-main-\x60;32* R-args-\x60;32* R-Array-\x60;32* R-String-\x60;32*)
                      (function FunctionDefinition)
                      (#\nul (("Scala" "Keyword" "sealed ")))
                      ("Scala"
                       "FunctionSignature"
                       R-main-\x60;32*
                       #\nul
                       ("Scala"
                        "ParamClauses"
                        (("Scala"
                          "ParamClause"
                          ("Scala"
                           "Params"
                           (("Scala"
                             "Param"
                             #\nul
                             R-args-\x60;32*
                             ("Scala"
                              "RepeatedParamType"
                              ("Scala"
                               "Type"
                               #\nul
                               ("Scala"
                                "InfixType"
                                ("Scala"
                                 "CompoundType"
                                 ("Scala"
                                  "AnnotType"
                                  ("Scala"
                                   "SimpleType"
                                   ("Scala" "StableId" (R-Array-\x60;32*))
                                   (("Scala"
                                     "TypeArgs"
                                     ("Scala"
                                      "Types"
                                      (("Scala"
                                        "Type"
                                        #\nul
                                        ("Scala"
                                         "InfixType"
                                         ("Scala"
                                          "CompoundType"
                                          ("Scala"
                                           "AnnotType"
                                           ("Scala"
                                            "SimpleType"
                                            ("Scala" "StableId" (R-String-\x60;32*))
                                            #\nul)
                                           #\nul)
                                          #\nul
                                          #\nul)
                                         #\nul
                                         #\nul)))))))
                                  #\nul)
                                 #\nul
                                 #\nul)
                                #\nul
                                #\nul))
                              #\nul)
                             #\nul)))))
                        #\nul))
                      ("Scala"
                       "Type"
                       #\nul
                       ("Scala"
                        "InfixType"
                        ("Scala"
                         "CompoundType"
                         ("Scala"
                          "AnnotType"
                          ("Scala" "SimpleType" ("Scala" "StableId" (R-Unit-)) #\nul)
                          #\nul)
                         #\nul
                         #\nul)
                        #\nul
                        #\nul))
                      ("Scala"
                       "PostfixExpression"
                       ("Scala"
                        "InfixExpression"
                        ("Scala"
                         "PrefixExpression"
                         #\nul
                         ("Scala"
                          "BlockExpression"
                          ("Scala"
                           "Block"
                           (letrec* ((V-tb\x60;34*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ("Scala"
                                         "Type"
                                         #\nul
                                         ("Scala"
                                          "InfixType"
                                          ("Scala"
                                           "CompoundType"
                                           ("Scala"
                                            "AnnotType"
                                            ("Scala"
                                             "SimpleType"
                                             ("Scala" "StableId" (R-Int-))
                                             #\nul)
                                            #\nul)
                                           #\nul
                                           #\nul)
                                          #\nul
                                          #\nul))
                                        (#\nul #\nul)))
                                     (V-f\x60;34*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ("Scala"
                                         "Type"
                                         #\nul
                                         ("Scala"
                                          "InfixType"
                                          ("Scala"
                                           "CompoundType"
                                           ("Scala"
                                            "AnnotType"
                                            ("Scala"
                                             "SimpleType"
                                             ("Scala" "StableId" (R-Int-))
                                             #\nul)
                                            #\nul)
                                           #\nul
                                           #\nul)
                                          #\nul
                                          #\nul))
                                        (#\nul ("Scala" "Keyword" "implicit "))))
                                     (V-b\x60;34*
                                       ((var variable)
                                        (#\nul)
                                        ("Scala"
                                         "PostfixExpression"
                                         ("Scala"
                                          "InfixExpression"
                                          ("Scala"
                                           "PrefixExpression"
                                           #\nul
                                           ("Scala"
                                            "SimpleExpression"
                                            ("Scala" "literalSimpleExpression" 1000 #\nul)
                                            #\nul))
                                          #\nul
                                          #\nul)
                                         #\nul)
                                        (#\nul ("Scala" "Keyword" "lazy "))))
                                     (V-c\x60;34*
                                       ((val variable)
                                        (#\nul)
                                        ("Scala"
                                         "PostfixExpression"
                                         ("Scala"
                                          "InfixExpression"
                                          ("Scala"
                                           "PrefixExpression"
                                           #\nul
                                           ("Scala"
                                            "SimpleExpression"
                                            ("Scala" "literalSimpleExpression" 1001 #\nul)
                                            #\nul))
                                          #\nul
                                          #\nul)
                                         #\nul)
                                        (#\nul #\nul)))
                                     (V-d\x60;34*
                                       ((var variable)
                                        (#\nul)
                                        ("Scala"
                                         "PostfixExpression"
                                         ("Scala"
                                          "InfixExpression"
                                          ("Scala"
                                           "PrefixExpression"
                                           #\nul
                                           ("Scala"
                                            "SimpleExpression"
                                            ("Scala" "literalSimpleExpression" 1000 #\nul)
                                            #\nul))
                                          #\nul
                                          #\nul)
                                         #\nul)
                                        (#\nul ("Scala" "Keyword" "lazy "))))
                                     (V-r\x60;34*
                                       ((var variable)
                                        (#\nul)
                                        ("Scala"
                                         "PostfixExpression"
                                         ("Scala"
                                          "InfixExpression"
                                          ("Scala"
                                           "PrefixExpression"
                                           #\nul
                                           ("Scala"
                                            "SimpleExpression"
                                            ("Scala" "literalSimpleExpression" 1001 #\nul)
                                            #\nul))
                                          #\nul
                                          #\nul)
                                         #\nul)
                                        (#\nul #\nul)))
                                     (V-doIt2\x60;34*
                                       ((lambda (V-doIt2\x60;35*)
                                          (function Procedure)
                                          (#\nul ("Scala" "Keyword" "lazy "))
                                          ("Scala"
                                           "FunctionSignature"
                                           V-doIt2\x60;35*
                                           #\nul
                                           ("Scala"
                                            "ParamClauses"
                                            (("Scala" "ParamClause" #\nul))
                                            #\nul))
                                          #\nul
                                          ("Scala"
                                           "Block"
                                           (let ()
                                             (("Scala"
                                               "PostfixExpression"
                                               ("Scala"
                                                "InfixExpression"
                                                ("Scala"
                                                 "PrefixExpression"
                                                 #\nul
                                                 ("Scala"
                                                  "SimpleExpression"
                                                  ("Scala"
                                                   "idSeqSimpleExpression"
                                                   V-println
                                                   ("Scala"
                                                    "FunctionApplicationPostfix"
                                                    ("Scala"
                                                     "ArgumentExpression"
                                                     ("Scala"
                                                      "Exprs"
                                                      (("Scala"
                                                        "PostfixExpression"
                                                        ("Scala"
                                                         "InfixExpression"
                                                         ("Scala"
                                                          "PrefixExpression"
                                                          #\nul
                                                          ("Scala"
                                                           "SimpleExpression"
                                                           ("Scala"
                                                            "literalSimpleExpression"
                                                            4
                                                            #\nul)
                                                           #\nul))
                                                         #\nul
                                                         #\nul)
                                                        #\nul))))
                                                    #\nul))
                                                  #\nul))
                                                #\nul
                                                #\nul)
                                               #\nul))
                                             #\nul)))))
                                     (V-a\x60;34*
                                       ((val variable)
                                        (#\nul)
                                        (#\nul
                                         (("Scala"
                                           "PostfixExpression"
                                           ("Scala"
                                            "InfixExpression"
                                            ("Scala"
                                             "PrefixExpression"
                                             #\nul
                                             ("Scala"
                                              "SimpleExpression"
                                              ("Scala"
                                               "TupleExpression"
                                               ("Scala"
                                                "Exprs"
                                                (("Scala"
                                                  "AnonymousFunction"
                                                  (lambda (V-f\x60;38\x60;39*)
                                                    (#\nul)
                                                    ("Scala"
                                                     "PostfixExpression"
                                                     ("Scala"
                                                      "InfixExpression"
                                                      ("Scala"
                                                       "PrefixExpression"
                                                       #\nul
                                                       ("Scala"
                                                        "BlockExpression"
                                                        ("Scala"
                                                         "Block"
                                                         (letrec* ((V-tb\x60;38\x60;41*
                                                                     ((type TypeDefinition)
                                                                      (#\nul)
                                                                      ("Scala"
                                                                       "Type"
                                                                       #\nul
                                                                       ("Scala"
                                                                        "InfixType"
                                                                        ("Scala"
                                                                         "CompoundType"
                                                                         ("Scala"
                                                                          "AnnotType"
                                                                          ("Scala"
                                                                           "SimpleType"
                                                                           ("Scala"
                                                                            "StableId"
                                                                            (V-tb\x60;34*))
                                                                           #\nul)
                                                                          #\nul)
                                                                         #\nul
                                                                         #\nul)
                                                                        #\nul
                                                                        #\nul))
                                                                      (#\nul #\nul)))
                                                                   (V-d\x60;38\x60;41*
                                                                     ((val variable)
                                                                      (("Scala"
                                                                        "Type"
                                                                        #\nul
                                                                        ("Scala"
                                                                         "InfixType"
                                                                         ("Scala"
                                                                          "CompoundType"
                                                                          ("Scala"
                                                                           "AnnotType"
                                                                           ("Scala"
                                                                            "SimpleType"
                                                                            ("Scala"
                                                                             "StableId"
                                                                             (V-tb\x60;38\x60;41*))
                                                                            #\nul)
                                                                           #\nul)
                                                                          #\nul
                                                                          #\nul)
                                                                         #\nul
                                                                         #\nul)))
                                                                      ("Scala"
                                                                       "PostfixExpression"
                                                                       ("Scala"
                                                                        "InfixExpression"
                                                                        ("Scala"
                                                                         "PrefixExpression"
                                                                         #\nul
                                                                         ("Scala"
                                                                          "SimpleExpression"
                                                                          ("Scala"
                                                                           "literalSimpleExpression"
                                                                           3
                                                                           #\nul)
                                                                          #\nul))
                                                                        #\nul
                                                                        #\nul)
                                                                       #\nul)
                                                                      (#\nul #\nul)))
                                                                   (V-doIt\x60;38\x60;41*
                                                                     ((lambda (V-doIt\x60;38\x60;42*
                                                                                V-d\x60;38\x60;42*
                                                                                R-Int-\x60;38\x60;42*)
                                                                        (function Procedure)
                                                                        (#\nul #\nul)
                                                                        ("Scala"
                                                                         "FunctionSignature"
                                                                         V-doIt\x60;38\x60;42*
                                                                         #\nul
                                                                         ("Scala"
                                                                          "ParamClauses"
                                                                          (("Scala"
                                                                            "ParamClause"
                                                                            ("Scala"
                                                                             "Params"
                                                                             (("Scala"
                                                                               "Param"
                                                                               #\nul
                                                                               V-d\x60;38\x60;42*
                                                                               ("Scala"
                                                                                "RepeatedParamType"
                                                                                ("Scala"
                                                                                 "Type"
                                                                                 #\nul
                                                                                 ("Scala"
                                                                                  "InfixType"
                                                                                  ("Scala"
                                                                                   "CompoundType"
                                                                                   ("Scala"
                                                                                    "AnnotType"
                                                                                    ("Scala"
                                                                                     "SimpleType"
                                                                                     ("Scala"
                                                                                      "StableId"
                                                                                      (R-Int-\x60;38\x60;42*))
                                                                                     #\nul)
                                                                                    #\nul)
                                                                                   #\nul
                                                                                   #\nul)
                                                                                  #\nul
                                                                                  #\nul))
                                                                                #\nul)
                                                                               #\nul)))))
                                                                          #\nul))
                                                                        #\nul
                                                                        ("Scala"
                                                                         "Block"
                                                                         (letrec* ((V-a\x60;38\x60;44*
                                                                                     ((val variable)
                                                                                      (#\nul)
                                                                                      ("Scala"
                                                                                       "PostfixExpression"
                                                                                       ("Scala"
                                                                                        "InfixExpression"
                                                                                        ("Scala"
                                                                                         "PrefixExpression"
                                                                                         #\nul
                                                                                         ("Scala"
                                                                                          "SimpleExpression"
                                                                                          ("Scala"
                                                                                           "literalSimpleExpression"
                                                                                           3
                                                                                           #\nul)
                                                                                          #\nul))
                                                                                        (V-+)
                                                                                        (("Scala"
                                                                                          "InfixExpression"
                                                                                          ("Scala"
                                                                                           "PrefixExpression"
                                                                                           #\nul
                                                                                           ("Scala"
                                                                                            "SimpleExpression"
                                                                                            ("Scala"
                                                                                             "idSeqSimpleExpression"
                                                                                             V-d\x60;38\x60;42*
                                                                                             #\nul)
                                                                                            #\nul))
                                                                                          #\nul
                                                                                          #\nul)))
                                                                                       #\nul)
                                                                                      (#\nul
                                                                                       #\nul))))
                                                                           (#\nul
                                                                            ("Scala"
                                                                             "PostfixExpression"
                                                                             ("Scala"
                                                                              "InfixExpression"
                                                                              ("Scala"
                                                                               "PrefixExpression"
                                                                               #\nul
                                                                               ("Scala"
                                                                                "SimpleExpression"
                                                                                ("Scala"
                                                                                 "idSeqSimpleExpression"
                                                                                 V-println
                                                                                 ("Scala"
                                                                                  "FunctionApplicationPostfix"
                                                                                  ("Scala"
                                                                                   "ArgumentExpression"
                                                                                   ("Scala"
                                                                                    "Exprs"
                                                                                    (("Scala"
                                                                                      "PostfixExpression"
                                                                                      ("Scala"
                                                                                       "InfixExpression"
                                                                                       ("Scala"
                                                                                        "PrefixExpression"
                                                                                        #\nul
                                                                                        ("Scala"
                                                                                         "SimpleExpression"
                                                                                         ("Scala"
                                                                                          "idSeqSimpleExpression"
                                                                                          V-a\x60;38\x60;44*
                                                                                          #\nul)
                                                                                         #\nul))
                                                                                       #\nul
                                                                                       #\nul)
                                                                                      #\nul))))
                                                                                  #\nul))
                                                                                #\nul))
                                                                              #\nul
                                                                              #\nul)
                                                                             #\nul))
                                                                           #\nul))))))
                                                           (#\nul
                                                            #\nul
                                                            #\nul
                                                            ("Scala"
                                                             "IfStatement"
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "idSeqSimpleExpression"
                                                                  V-f\x60;38\x60;39*
                                                                  #\nul)
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul)
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "idSeqSimpleExpression"
                                                                  ("Scala"
                                                                   "PostfixExpression"
                                                                   ("Scala"
                                                                    "InfixExpression"
                                                                    ("Scala"
                                                                     "PrefixExpression"
                                                                     #\nul
                                                                     ("Scala"
                                                                      "SimpleExpression"
                                                                      ("Scala"
                                                                       "literalSimpleExpression"
                                                                       10
                                                                       #\nul)
                                                                      #\nul))
                                                                    #\nul
                                                                    #\nul)
                                                                   #\nul)
                                                                  #\nul)
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul)
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "idSeqSimpleExpression"
                                                                  V-doIt\x60;38\x60;41*
                                                                  ("Scala"
                                                                   "FunctionApplicationPostfix"
                                                                   ("Scala"
                                                                    "ArgumentExpression"
                                                                    ("Scala"
                                                                     "Exprs"
                                                                     (("Scala"
                                                                       "PostfixExpression"
                                                                       ("Scala"
                                                                        "InfixExpression"
                                                                        ("Scala"
                                                                         "PrefixExpression"
                                                                         #\nul
                                                                         ("Scala"
                                                                          "SimpleExpression"
                                                                          ("Scala"
                                                                           "idSeqSimpleExpression"
                                                                           V-d\x60;38\x60;41*
                                                                           #\nul)
                                                                          #\nul))
                                                                        #\nul
                                                                        #\nul)
                                                                       #\nul))))
                                                                   #\nul))
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul)))
                                                           #\nul))))
                                                      #\nul
                                                      #\nul)
                                                     #\nul)))))
                                               ("Scala"
                                                "FunctionApplicationPostfix"
                                                ("Scala"
                                                 "ArgumentExpression"
                                                 ("Scala"
                                                  "Exprs"
                                                  (("Scala"
                                                    "PostfixExpression"
                                                    ("Scala"
                                                     "InfixExpression"
                                                     ("Scala"
                                                      "PrefixExpression"
                                                      #\nul
                                                      ("Scala"
                                                       "SimpleExpression"
                                                       ("Scala"
                                                        "idSeqSimpleExpression"
                                                        ("Scala"
                                                         "PostfixExpression"
                                                         ("Scala"
                                                          "InfixExpression"
                                                          ("Scala"
                                                           "PrefixExpression"
                                                           #\nul
                                                           ("Scala"
                                                            "SimpleExpression"
                                                            ("Scala"
                                                             "literalSimpleExpression"
                                                             10
                                                             #\nul)
                                                            #\nul))
                                                          #\nul
                                                          #\nul)
                                                         #\nul)
                                                        #\nul)
                                                       #\nul))
                                                     #\nul
                                                     #\nul)
                                                    #\nul))))
                                                #\nul))
                                              #\nul))
                                            #\nul
                                            #\nul)
                                           #\nul))
                                         #\nul)
                                        (#\nul #\nul))))
                             (#\nul
                              #\nul
                              #\nul
                              #\nul
                              #\nul
                              #\nul
                              #\nul
                              #\nul
                              #\nul
                              #\nul
                              #\nul
                              #\nul
                              ("Scala"
                               "PostfixExpression"
                               ("Scala"
                                "InfixExpression"
                                ("Scala"
                                 "PrefixExpression"
                                 #\nul
                                 ("Scala"
                                  "SimpleExpression"
                                  ("Scala"
                                   "idSeqSimpleExpression"
                                   V-println
                                   ("Scala"
                                    "FunctionApplicationPostfix"
                                    ("Scala"
                                     "ArgumentExpression"
                                     ("Scala"
                                      "Exprs"
                                      (("Scala"
                                        "PostfixExpression"
                                        ("Scala"
                                         "InfixExpression"
                                         ("Scala"
                                          "PrefixExpression"
                                          #\nul
                                          ("Scala"
                                           "SimpleExpression"
                                           ("Scala" "idSeqSimpleExpression" V-a\x60;34* #\nul)
                                           #\nul))
                                         #\nul
                                         #\nul)
                                        #\nul))))
                                    #\nul))
                                  #\nul))
                                #\nul
                                #\nul)
                               #\nul))
                             #\nul))))
                        #\nul
                        #\nul)
                       #\nul))))
                 (V-doIt2\x60;28*
                   ((lambda (V-doIt2\x60;48*)
                      (function FunctionDeclaration)
                      (#\nul (("Scala" "Keyword" "lazy ")))
                      ("Scala"
                       "FunctionSignature"
                       V-doIt2\x60;48*
                       #\nul
                       ("Scala" "ParamClauses" (("Scala" "ParamClause" #\nul)) #\nul))
                      ("Scala"
                       "Type"
                       #\nul
                       ("Scala"
                        "InfixType"
                        ("Scala"
                         "CompoundType"
                         ("Scala"
                          "AnnotType"
                          ("Scala" "SimpleType" ("Scala" "StableId" (R-Int-)) #\nul)
                          #\nul)
                         #\nul
                         #\nul)
                        #\nul
                        #\nul))
                      #\nul))))
         #\nul
         (#\nul #\nul #\nul #\nul #\nul #\nul #\nul #\nul #\nul #\nul #\nul #\nul #\nul #\nul)))))))
  #\nul)