(begin
  ("Scala"
   "TopStat"
   #\nul
   #\nul
   ("Scala"
    "ObjectTemplateDefinition"
    #\nul
    ("Scala"
     "ObjectDefinition"
     V-Rec_Func
     ("Scala"
      "ClassTemplateOpt"
      #\nul
      ("Scala"
       "TemplateBody"
       (letrec* ((R-main-\x60;28*
                   ((lambda ()
                      (function FunctionDefinition)
                      (#\nul #\nul)
                      ("Scala"
                       "FunctionSignature"
                       R-main-\x60;28*
                       #\nul
                       ("Scala"
                        "ParamClauses"
                        (("Scala"
                          "ParamClause"
                          ("Scala"
                           "Params"
                           (("Scala"
                             "Param"
                             #\nul
                             R-args-
                             ("Scala"
                              "RepeatedParamType"
                              ("Scala"
                               "Type"
                               #\nul
                               ("Scala"
                                "InfixType"
                                ("Scala"
                                 "CompoundType"
                                 ("Scala"
                                  "AnnotType"
                                  ("Scala"
                                   "SimpleType"
                                   ("Scala" "StableId" (R-Array-))
                                   (("Scala"
                                     "TypeArgs"
                                     ("Scala"
                                      "Types"
                                      (("Scala"
                                        "Type"
                                        #\nul
                                        ("Scala"
                                         "InfixType"
                                         ("Scala"
                                          "CompoundType"
                                          ("Scala"
                                           "AnnotType"
                                           ("Scala"
                                            "SimpleType"
                                            ("Scala" "StableId" (R-String-))
                                            #\nul)
                                           #\nul)
                                          #\nul
                                          #\nul)
                                         #\nul
                                         #\nul)))))))
                                  #\nul)
                                 #\nul
                                 #\nul)
                                #\nul
                                #\nul))
                              #\nul)
                             #\nul)))))
                        #\nul))
                      ("Scala"
                       "Type"
                       #\nul
                       ("Scala"
                        "InfixType"
                        ("Scala"
                         "CompoundType"
                         ("Scala"
                          "AnnotType"
                          ("Scala" "SimpleType" ("Scala" "StableId" (R-Unit-)) #\nul)
                          #\nul)
                         #\nul
                         #\nul)
                        #\nul
                        #\nul))
                      ("Scala"
                       "PostfixExpression"
                       ("Scala"
                        "InfixExpression"
                        ("Scala"
                         "PrefixExpression"
                         #\nul
                         ("Scala"
                          "BlockExpression"
                          ("Scala"
                           "Block"
                           (letrec* ((V-A\x60;31*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ("Scala"
                                         "Type"
                                         #\nul
                                         ("Scala"
                                          "InfixType"
                                          ("Scala"
                                           "CompoundType"
                                           ("Scala"
                                            "AnnotType"
                                            ("Scala"
                                             "SimpleType"
                                             ("Scala" "StableId" (R-Int-))
                                             #\nul)
                                            #\nul)
                                           #\nul
                                           #\nul)
                                          #\nul
                                          #\nul))
                                        (#\nul #\nul)))
                                     (V-a\x60;31*
                                       ((lambda ()
                                          (function Procedure)
                                          (#\nul #\nul)
                                          ("Scala"
                                           "FunctionSignature"
                                           V-a\x60;31*
                                           #\nul
                                           ("Scala"
                                            "ParamClauses"
                                            (("Scala"
                                              "ParamClause"
                                              ("Scala"
                                               "Params"
                                               (("Scala"
                                                 "Param"
                                                 #\nul
                                                 V-c
                                                 ("Scala"
                                                  "RepeatedParamType"
                                                  ("Scala"
                                                   "Type"
                                                   #\nul
                                                   ("Scala"
                                                    "InfixType"
                                                    ("Scala"
                                                     "CompoundType"
                                                     ("Scala"
                                                      "AnnotType"
                                                      ("Scala"
                                                       "SimpleType"
                                                       ("Scala" "StableId" (V-A\x60;31*))
                                                       #\nul)
                                                      #\nul)
                                                     #\nul
                                                     #\nul)
                                                    #\nul
                                                    #\nul))
                                                  #\nul)
                                                 #\nul)))))
                                            #\nul))
                                          #\nul
                                          ("Scala"
                                           "Block"
                                           (let ()
                                             (("Scala"
                                               "PostfixExpression"
                                               ("Scala"
                                                "InfixExpression"
                                                ("Scala"
                                                 "PrefixExpression"
                                                 #\nul
                                                 ("Scala"
                                                  "SimpleExpression"
                                                  ("Scala"
                                                   "idSeqSimpleExpression"
                                                   V-println
                                                   ("Scala"
                                                    "FunctionApplicationPostfix"
                                                    ("Scala"
                                                     "ArgumentExpression"
                                                     ("Scala"
                                                      "Exprs"
                                                      (("Scala"
                                                        "PostfixExpression"
                                                        ("Scala"
                                                         "InfixExpression"
                                                         ("Scala"
                                                          "PrefixExpression"
                                                          #\nul
                                                          ("Scala"
                                                           "SimpleExpression"
                                                           ("Scala"
                                                            "idSeqSimpleExpression"
                                                            V-c
                                                            #\nul)
                                                           #\nul))
                                                         #\nul
                                                         #\nul)
                                                        #\nul))))
                                                    #\nul))
                                                  #\nul))
                                                #\nul
                                                #\nul)
                                               #\nul)
                                              ("Scala"
                                               "PostfixExpression"
                                               ("Scala"
                                                "InfixExpression"
                                                ("Scala"
                                                 "PrefixExpression"
                                                 #\nul
                                                 ("Scala"
                                                  "SimpleExpression"
                                                  ("Scala"
                                                   "idSeqSimpleExpression"
                                                   V-b\x60;31*
                                                   ("Scala"
                                                    "FunctionApplicationPostfix"
                                                    ("Scala"
                                                     "ArgumentExpression"
                                                     ("Scala"
                                                      "Exprs"
                                                      (("Scala"
                                                        "PostfixExpression"
                                                        ("Scala"
                                                         "InfixExpression"
                                                         ("Scala"
                                                          "PrefixExpression"
                                                          #\nul
                                                          ("Scala"
                                                           "SimpleExpression"
                                                           ("Scala"
                                                            "idSeqSimpleExpression"
                                                            V-c
                                                            #\nul)
                                                           #\nul))
                                                         (V-+)
                                                         (("Scala"
                                                           "InfixExpression"
                                                           ("Scala"
                                                            "PrefixExpression"
                                                            #\nul
                                                            ("Scala"
                                                             "SimpleExpression"
                                                             ("Scala"
                                                              "literalSimpleExpression"
                                                              1
                                                              #\nul)
                                                             #\nul))
                                                           #\nul
                                                           #\nul)))
                                                        #\nul))))
                                                    #\nul))
                                                  #\nul))
                                                #\nul
                                                #\nul)
                                               #\nul))
                                             #\nul)))))
                                     (V-b\x60;31*
                                       ((lambda ()
                                          (function Procedure)
                                          (#\nul #\nul)
                                          ("Scala"
                                           "FunctionSignature"
                                           V-b\x60;31*
                                           #\nul
                                           ("Scala"
                                            "ParamClauses"
                                            (("Scala"
                                              "ParamClause"
                                              ("Scala"
                                               "Params"
                                               (("Scala"
                                                 "Param"
                                                 #\nul
                                                 V-c
                                                 ("Scala"
                                                  "RepeatedParamType"
                                                  ("Scala"
                                                   "Type"
                                                   #\nul
                                                   ("Scala"
                                                    "InfixType"
                                                    ("Scala"
                                                     "CompoundType"
                                                     ("Scala"
                                                      "AnnotType"
                                                      ("Scala"
                                                       "SimpleType"
                                                       ("Scala" "StableId" (V-A\x60;31*))
                                                       #\nul)
                                                      #\nul)
                                                     #\nul
                                                     #\nul)
                                                    #\nul
                                                    #\nul))
                                                  #\nul)
                                                 #\nul)))))
                                            #\nul))
                                          #\nul
                                          ("Scala"
                                           "Block"
                                           (let ()
                                             (("Scala"
                                               "PostfixExpression"
                                               ("Scala"
                                                "InfixExpression"
                                                ("Scala"
                                                 "PrefixExpression"
                                                 #\nul
                                                 ("Scala"
                                                  "SimpleExpression"
                                                  ("Scala"
                                                   "idSeqSimpleExpression"
                                                   V-println
                                                   ("Scala"
                                                    "FunctionApplicationPostfix"
                                                    ("Scala"
                                                     "ArgumentExpression"
                                                     ("Scala"
                                                      "Exprs"
                                                      (("Scala"
                                                        "PostfixExpression"
                                                        ("Scala"
                                                         "InfixExpression"
                                                         ("Scala"
                                                          "PrefixExpression"
                                                          #\nul
                                                          ("Scala"
                                                           "SimpleExpression"
                                                           ("Scala"
                                                            "idSeqSimpleExpression"
                                                            V-c
                                                            #\nul)
                                                           #\nul))
                                                         #\nul
                                                         #\nul)
                                                        #\nul))))
                                                    #\nul))
                                                  #\nul))
                                                #\nul
                                                #\nul)
                                               #\nul)
                                              ("Scala"
                                               "PostfixExpression"
                                               ("Scala"
                                                "InfixExpression"
                                                ("Scala"
                                                 "PrefixExpression"
                                                 #\nul
                                                 ("Scala"
                                                  "SimpleExpression"
                                                  ("Scala"
                                                   "idSeqSimpleExpression"
                                                   V-a\x60;31*
                                                   ("Scala"
                                                    "FunctionApplicationPostfix"
                                                    ("Scala"
                                                     "ArgumentExpression"
                                                     ("Scala"
                                                      "Exprs"
                                                      (("Scala"
                                                        "PostfixExpression"
                                                        ("Scala"
                                                         "InfixExpression"
                                                         ("Scala"
                                                          "PrefixExpression"
                                                          #\nul
                                                          ("Scala"
                                                           "SimpleExpression"
                                                           ("Scala"
                                                            "idSeqSimpleExpression"
                                                            V-c
                                                            #\nul)
                                                           #\nul))
                                                         (V-+)
                                                         (("Scala"
                                                           "InfixExpression"
                                                           ("Scala"
                                                            "PrefixExpression"
                                                            #\nul
                                                            ("Scala"
                                                             "SimpleExpression"
                                                             ("Scala"
                                                              "literalSimpleExpression"
                                                              2
                                                              #\nul)
                                                             #\nul))
                                                           #\nul
                                                           #\nul)))
                                                        #\nul))))
                                                    #\nul))
                                                  #\nul))
                                                #\nul
                                                #\nul)
                                               #\nul))
                                             #\nul))))))
                             (#\nul #\nul #\nul)
                             #\nul))))
                        #\nul
                        #\nul)
                       #\nul)))))
         #\nul
         (#\nul #\nul)))))))
  #\nul)