(begin
  ("Scala"
   "TopStat"
   #\nul
   #\nul
   ("Scala"
    "ObjectTemplateDefinition"
    #\nul
    ("Scala"
     "ObjectDefinition"
     V-Append1
     ("Scala"
      "ClassTemplateOpt"
      #\nul
      ("Scala"
       "TemplateBody"
       (letrec* ((V-ta\x60;28* ((type TypeDeclaration) (#\nul #\nul #\nul) #\nul))
                 (V-tta\x60;28*
                   ((val variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (V-Int)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    ("Scala"
                     "PostfixExpression"
                     ("Scala"
                      "InfixExpression"
                      ("Scala"
                       "PrefixExpression"
                       #\nul
                       ("Scala"
                        "SimpleExpression"
                        ("Scala" "literalSimpleExpression" 3 #\nul)
                        #\nul))
                      #\nul
                      #\nul)
                     #\nul)
                    #\nul))
                 (V-ttb\x60;28*
                   ((var variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (V-Int)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    #\nul))
                 (V-main\x60;28*
                   ((lambda ()
                      (function FunctionDefinition)
                      ("Scala"
                       "FunctionSignature"
                       V-main\x60;28*
                       #\nul
                       ("Scala"
                        "ParamClauses"
                        (("Scala"
                          "ParamClause"
                          ("Scala"
                           "Params"
                           (("Scala"
                             "Param"
                             #\nul
                             V-args
                             ("Scala"
                              "RepeatedParamType"
                              ("Scala"
                               "Type"
                               #\nul
                               ("Scala"
                                "InfixType"
                                ("Scala"
                                 "CompoundType"
                                 ("Scala"
                                  "AnnotType"
                                  ("Scala"
                                   "SimpleType"
                                   ("Scala" "StableId" (V-Array))
                                   (("Scala"
                                     "TypeArgs"
                                     ("Scala"
                                      "Types"
                                      (("Scala"
                                        "Type"
                                        #\nul
                                        ("Scala"
                                         "InfixType"
                                         ("Scala"
                                          "CompoundType"
                                          ("Scala"
                                           "AnnotType"
                                           ("Scala"
                                            "SimpleType"
                                            ("Scala" "StableId" (V-String))
                                            #\nul)
                                           #\nul)
                                          #\nul
                                          #\nul)
                                         #\nul
                                         #\nul)))))))
                                  #\nul)
                                 #\nul
                                 #\nul)
                                #\nul
                                #\nul))
                              #\nul)
                             #\nul)))))
                        #\nul))
                      ("Scala"
                       "Type"
                       #\nul
                       ("Scala"
                        "InfixType"
                        ("Scala"
                         "CompoundType"
                         ("Scala"
                          "AnnotType"
                          ("Scala" "SimpleType" ("Scala" "StableId" (V-Unit)) #\nul)
                          #\nul)
                         #\nul
                         #\nul)
                        #\nul
                        #\nul))
                      ("Scala"
                       "PostfixExpression"
                       ("Scala"
                        "InfixExpression"
                        ("Scala"
                         "PrefixExpression"
                         #\nul
                         ("Scala"
                          "BlockExpression"
                          ("Scala"
                           "Block"
                           (letrec* ((V-tb\x60;31*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ("Scala"
                                         "Type"
                                         #\nul
                                         ("Scala"
                                          "InfixType"
                                          ("Scala"
                                           "CompoundType"
                                           ("Scala"
                                            "AnnotType"
                                            ("Scala"
                                             "SimpleType"
                                             ("Scala" "StableId" (V-Int))
                                             #\nul)
                                            #\nul)
                                           #\nul
                                           #\nul)
                                          #\nul
                                          #\nul))))
                                     (V-f\x60;31*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ("Scala"
                                         "Type"
                                         #\nul
                                         ("Scala"
                                          "InfixType"
                                          ("Scala"
                                           "CompoundType"
                                           ("Scala"
                                            "AnnotType"
                                            ("Scala"
                                             "SimpleType"
                                             ("Scala" "StableId" (V-Int))
                                             #\nul)
                                            #\nul)
                                           #\nul
                                           #\nul)
                                          #\nul
                                          #\nul))))
                                     (V-b\x60;31*
                                       ((val variable)
                                        (#\nul)
                                        ("Scala"
                                         "PostfixExpression"
                                         ("Scala"
                                          "InfixExpression"
                                          ("Scala"
                                           "PrefixExpression"
                                           #\nul
                                           ("Scala"
                                            "SimpleExpression"
                                            ("Scala" "literalSimpleExpression" 1000 #\nul)
                                            #\nul))
                                          #\nul
                                          #\nul)
                                         #\nul)
                                        #\nul))
                                     (V-a\x60;31*
                                       ((val variable)
                                        (#\nul)
                                        (#\nul
                                         (("Scala"
                                           "PostfixExpression"
                                           ("Scala"
                                            "InfixExpression"
                                            ("Scala"
                                             "PrefixExpression"
                                             #\nul
                                             ("Scala"
                                              "SimpleExpression"
                                              ("Scala"
                                               "TupleExpression"
                                               ("Scala"
                                                "Exprs"
                                                (("Scala"
                                                  "AnonymousFunction"
                                                  (lambda (V-f\x60;32\x60;33*)
                                                    (#\nul)
                                                    ("Scala"
                                                     "PostfixExpression"
                                                     ("Scala"
                                                      "InfixExpression"
                                                      ("Scala"
                                                       "PrefixExpression"
                                                       #\nul
                                                       ("Scala"
                                                        "BlockExpression"
                                                        ("Scala"
                                                         "Block"
                                                         (letrec* ((V-tb\x60;32\x60;35*
                                                                     ((type TypeDefinition)
                                                                      (#\nul)
                                                                      ("Scala"
                                                                       "Type"
                                                                       #\nul
                                                                       ("Scala"
                                                                        "InfixType"
                                                                        ("Scala"
                                                                         "CompoundType"
                                                                         ("Scala"
                                                                          "AnnotType"
                                                                          ("Scala"
                                                                           "SimpleType"
                                                                           ("Scala"
                                                                            "StableId"
                                                                            (V-tb\x60;31*))
                                                                           #\nul)
                                                                          #\nul)
                                                                         #\nul
                                                                         #\nul)
                                                                        #\nul
                                                                        #\nul))))
                                                                   (V-d\x60;32\x60;35*
                                                                     ((val variable)
                                                                      (("Scala"
                                                                        "Type"
                                                                        #\nul
                                                                        ("Scala"
                                                                         "InfixType"
                                                                         ("Scala"
                                                                          "CompoundType"
                                                                          ("Scala"
                                                                           "AnnotType"
                                                                           ("Scala"
                                                                            "SimpleType"
                                                                            ("Scala"
                                                                             "StableId"
                                                                             (V-tb\x60;32\x60;35*))
                                                                            #\nul)
                                                                           #\nul)
                                                                          #\nul
                                                                          #\nul)
                                                                         #\nul
                                                                         #\nul)))
                                                                      ("Scala"
                                                                       "PostfixExpression"
                                                                       ("Scala"
                                                                        "InfixExpression"
                                                                        ("Scala"
                                                                         "PrefixExpression"
                                                                         #\nul
                                                                         ("Scala"
                                                                          "SimpleExpression"
                                                                          ("Scala"
                                                                           "literalSimpleExpression"
                                                                           3
                                                                           #\nul)
                                                                          #\nul))
                                                                        #\nul
                                                                        #\nul)
                                                                       #\nul)
                                                                      #\nul)))
                                                           (("Scala" "BlockStat" #\nul #\nul #\nul)
                                                            ("Scala"
                                                             "BlockStat"
                                                             #\nul
                                                             #\nul
                                                             (object Object))
                                                            ("Scala"
                                                             "IfStatement"
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "idSeqSimpleExpression"
                                                                  V-f\x60;32\x60;33*
                                                                  #\nul)
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul)
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "idSeqSimpleExpression"
                                                                  ("Scala"
                                                                   "PostfixExpression"
                                                                   ("Scala"
                                                                    "InfixExpression"
                                                                    ("Scala"
                                                                     "PrefixExpression"
                                                                     #\nul
                                                                     ("Scala"
                                                                      "SimpleExpression"
                                                                      ("Scala"
                                                                       "literalSimpleExpression"
                                                                       10
                                                                       #\nul)
                                                                      #\nul))
                                                                    #\nul
                                                                    #\nul)
                                                                   #\nul)
                                                                  #\nul)
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul)
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "idSeqSimpleExpression"
                                                                  V-d\x60;32\x60;35*
                                                                  #\nul)
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul)))
                                                           #\nul))))
                                                      #\nul
                                                      #\nul)
                                                     #\nul)))))
                                               ("Scala"
                                                "FunctionApplicationPostfix"
                                                ("Scala"
                                                 "ArgumentExpression"
                                                 ("Scala"
                                                  "Exprs"
                                                  (("Scala"
                                                    "PostfixExpression"
                                                    ("Scala"
                                                     "InfixExpression"
                                                     ("Scala"
                                                      "PrefixExpression"
                                                      #\nul
                                                      ("Scala"
                                                       "SimpleExpression"
                                                       ("Scala"
                                                        "idSeqSimpleExpression"
                                                        ("Scala"
                                                         "PostfixExpression"
                                                         ("Scala"
                                                          "InfixExpression"
                                                          ("Scala"
                                                           "PrefixExpression"
                                                           #\nul
                                                           ("Scala"
                                                            "SimpleExpression"
                                                            ("Scala"
                                                             "literalSimpleExpression"
                                                             10
                                                             #\nul)
                                                            #\nul))
                                                          #\nul
                                                          #\nul)
                                                         #\nul)
                                                        #\nul)
                                                       #\nul))
                                                     #\nul
                                                     #\nul)
                                                    #\nul))))
                                                #\nul))
                                              #\nul))
                                            #\nul
                                            #\nul)
                                           #\nul))
                                         #\nul)
                                        #\nul)))
                             (("Scala" "BlockStat" #\nul #\nul #\nul)
                              ("Scala" "BlockStat" #\nul #\nul #\nul)
                              ("Scala" "BlockStat" #\nul ("Scala" "Keyword" "lazy") (object Object))
                              #\nul
                              ("Scala" "BlockStat" #\nul #\nul (object Object))
                              ("Scala"
                               "PostfixExpression"
                               ("Scala"
                                "InfixExpression"
                                ("Scala"
                                 "PrefixExpression"
                                 #\nul
                                 ("Scala"
                                  "SimpleExpression"
                                  ("Scala"
                                   "idSeqSimpleExpression"
                                   V-println
                                   ("Scala"
                                    "FunctionApplicationPostfix"
                                    ("Scala"
                                     "ArgumentExpression"
                                     ("Scala"
                                      "Exprs"
                                      (("Scala"
                                        "PostfixExpression"
                                        ("Scala"
                                         "InfixExpression"
                                         ("Scala"
                                          "PrefixExpression"
                                          #\nul
                                          ("Scala"
                                           "SimpleExpression"
                                           ("Scala" "idSeqSimpleExpression" V-a\x60;31* #\nul)
                                           #\nul))
                                         #\nul
                                         #\nul)
                                        #\nul))))
                                    #\nul))
                                  #\nul))
                                #\nul
                                #\nul)
                               #\nul))
                             #\nul))))
                        #\nul
                        #\nul)
                       #\nul)))))
         #\nul
         (("Scala" "TemplateStatement" #\nul #\nul #\nul)
          ("Scala" "TemplateStatement" #\nul #\nul (object Object))
          ("Scala"
           "TemplateStatement"
           #\nul
           (("Scala" "AccessModifier" ("Scala" "Keyword" "private") #\nul))
           #\nul)
          ("Scala" "TemplateStatement" #\nul #\nul ("Scala" "Definition" #\nul))
          #\nul)))))))
  #\nul)