
(define (my-counter start)
  (let ((counter 0))
	(lambda ()
	  (display "generating ")
	  (display start)
	  (display " th counterMakers.")
	  (newline)
	  (set! start (+ start 1))
	  (lambda ()
		(display counter)
		(display " count.")
		(newline)
		(set! counter (+ counter 1))
		counter
		))))

(define my-mc (my-counter 0))
(define cm1 (my-mc))
(define cm2 (my-mc))
(define cm3 (my-mc))
(display (cm1))
(newline)
(display (cm1))
(newline)
(newline)
(display (cm2))
(newline)
(display (cm2))
(newline)
