(begin
  ("Scala"
   "TopStat"
   #\nul
   #\nul
   ("Scala"
    "ObjectTemplateDefinition"
    #\nul
    ("Scala"
     "ObjectDefinition"
     V-makeArray
     ("Scala"
      "ClassTemplateOpt"
      #\nul
      ("Scala"
       "TemplateBody"
       (letrec* ((R-main-\x60;28*
                   ((lambda ()
                      (function FunctionDefinition)
                      (#\nul #\nul)
                      ("Scala"
                       "FunctionSignature"
                       R-main-\x60;28*
                       #\nul
                       ("Scala"
                        "ParamClauses"
                        (("Scala"
                          "ParamClause"
                          ("Scala"
                           "Params"
                           (("Scala"
                             "Param"
                             #\nul
                             R-args-
                             ("Scala"
                              "RepeatedParamType"
                              ("Scala"
                               "Type"
                               #\nul
                               ("Scala"
                                "InfixType"
                                ("Scala"
                                 "CompoundType"
                                 ("Scala"
                                  "AnnotType"
                                  ("Scala"
                                   "SimpleType"
                                   ("Scala" "StableId" (R-Array-))
                                   (("Scala"
                                     "TypeArgs"
                                     ("Scala"
                                      "Types"
                                      (("Scala"
                                        "Type"
                                        #\nul
                                        ("Scala"
                                         "InfixType"
                                         ("Scala"
                                          "CompoundType"
                                          ("Scala"
                                           "AnnotType"
                                           ("Scala"
                                            "SimpleType"
                                            ("Scala" "StableId" (R-String-))
                                            #\nul)
                                           #\nul)
                                          #\nul
                                          #\nul)
                                         #\nul
                                         #\nul)))))))
                                  #\nul)
                                 #\nul
                                 #\nul)
                                #\nul
                                #\nul))
                              #\nul)
                             #\nul)))))
                        #\nul))
                      ("Scala"
                       "Type"
                       #\nul
                       ("Scala"
                        "InfixType"
                        ("Scala"
                         "CompoundType"
                         ("Scala"
                          "AnnotType"
                          ("Scala" "SimpleType" ("Scala" "StableId" (R-Unit-)) #\nul)
                          #\nul)
                         #\nul
                         #\nul)
                        #\nul
                        #\nul))
                      ("Scala"
                       "PostfixExpression"
                       ("Scala"
                        "InfixExpression"
                        ("Scala"
                         "PrefixExpression"
                         #\nul
                         ("Scala"
                          "BlockExpression"
                          ("Scala"
                           "Block"
                           (letrec* ((V-c\x60;31*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ("Scala"
                                         "Type"
                                         #\nul
                                         ("Scala"
                                          "InfixType"
                                          ("Scala"
                                           "CompoundType"
                                           ("Scala"
                                            "AnnotType"
                                            ("Scala"
                                             "SimpleType"
                                             ("Scala" "StableId" (R-Int-))
                                             #\nul)
                                            #\nul)
                                           #\nul
                                           #\nul)
                                          #\nul
                                          #\nul))
                                        (#\nul #\nul)))
                                     (V-b\x60;31*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ((#\nul
                                          ("Scala"
                                           "Type"
                                           #\nul
                                           ("Scala"
                                            "InfixType"
                                            ("Scala"
                                             "CompoundType"
                                             ("Scala"
                                              "AnnotType"
                                              ("Scala"
                                               "SimpleType"
                                               ("Scala" "StableId" (R-Int-))
                                               #\nul)
                                              #\nul)
                                             #\nul
                                             #\nul)
                                            #\nul
                                            #\nul))))
                                        (#\nul #\nul)))
                                     (V-d\x60;31*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ((#\nul
                                          ("Scala"
                                           "FunctionType"
                                           ("Scala"
                                            "FunctionArgTypes"
                                            (("Scala"
                                              "RepeatedParamType"
                                              ("Scala"
                                               "Type"
                                               #\nul
                                               ("Scala"
                                                "InfixType"
                                                ("Scala"
                                                 "CompoundType"
                                                 ("Scala"
                                                  "AnnotType"
                                                  ("Scala"
                                                   "SimpleType"
                                                   ("Scala" "StableId" (R-String-))
                                                   #\nul)
                                                  #\nul)
                                                 #\nul
                                                 #\nul)
                                                #\nul
                                                #\nul))
                                              #\nul)
                                             ("Scala"
                                              "RepeatedParamType"
                                              ((#\nul
                                                ("Scala"
                                                 "Type"
                                                 #\nul
                                                 ("Scala"
                                                  "InfixType"
                                                  ("Scala"
                                                   "CompoundType"
                                                   ("Scala"
                                                    "AnnotType"
                                                    ("Scala"
                                                     "SimpleType"
                                                     ("Scala" "StableId" (R-Int-))
                                                     #\nul)
                                                    #\nul)
                                                   #\nul
                                                   #\nul)
                                                  #\nul
                                                  #\nul))))
                                              #\nul)))
                                           ("Scala"
                                            "Type"
                                            #\nul
                                            ("Scala"
                                             "InfixType"
                                             ("Scala"
                                              "CompoundType"
                                              ("Scala"
                                               "AnnotType"
                                               ("Scala"
                                                "SimpleType"
                                                ("Scala" "StableId" (R-Double-))
                                                #\nul)
                                               #\nul)
                                              #\nul
                                              #\nul)
                                             #\nul
                                             #\nul)))))
                                        (#\nul #\nul)))
                                     (V-z\x60;31*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ((#\nul
                                          ((#\nul
                                            ("Scala"
                                             "FunctionType"
                                             ("Scala"
                                              "FunctionArgTypes"
                                              (("Scala"
                                                "RepeatedParamType"
                                                ("Scala"
                                                 "Type"
                                                 #\nul
                                                 ("Scala"
                                                  "InfixType"
                                                  ("Scala"
                                                   "CompoundType"
                                                   ("Scala"
                                                    "AnnotType"
                                                    ("Scala"
                                                     "SimpleType"
                                                     ("Scala" "StableId" (R-String-))
                                                     #\nul)
                                                    #\nul)
                                                   #\nul
                                                   #\nul)
                                                  #\nul
                                                  #\nul))
                                                #\nul)
                                               ("Scala"
                                                "RepeatedParamType"
                                                ((#\nul
                                                  ("Scala"
                                                   "Type"
                                                   #\nul
                                                   ("Scala"
                                                    "InfixType"
                                                    ("Scala"
                                                     "CompoundType"
                                                     ("Scala"
                                                      "AnnotType"
                                                      ("Scala"
                                                       "SimpleType"
                                                       ("Scala" "StableId" (R-Int-))
                                                       #\nul)
                                                      #\nul)
                                                     #\nul
                                                     #\nul)
                                                    #\nul
                                                    #\nul))))
                                                #\nul)))
                                             ("Scala"
                                              "Type"
                                              #\nul
                                              ("Scala"
                                               "InfixType"
                                               ("Scala"
                                                "CompoundType"
                                                ("Scala"
                                                 "AnnotType"
                                                 ("Scala"
                                                  "SimpleType"
                                                  ("Scala" "StableId" (R-Double-))
                                                  #\nul)
                                                 #\nul)
                                                #\nul
                                                #\nul)
                                               #\nul
                                               #\nul)))))))
                                        (#\nul #\nul)))
                                     (V-aa\x60;31*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ((#\nul
                                          ((#\nul
                                            ((#\nul
                                              ("Scala"
                                               "FunctionType"
                                               ("Scala"
                                                "FunctionArgTypes"
                                                (("Scala"
                                                  "RepeatedParamType"
                                                  ("Scala"
                                                   "Type"
                                                   #\nul
                                                   ("Scala"
                                                    "InfixType"
                                                    ("Scala"
                                                     "CompoundType"
                                                     ("Scala"
                                                      "AnnotType"
                                                      ("Scala"
                                                       "SimpleType"
                                                       ("Scala" "StableId" (R-String-))
                                                       #\nul)
                                                      #\nul)
                                                     #\nul
                                                     #\nul)
                                                    #\nul
                                                    #\nul))
                                                  #\nul)
                                                 ("Scala"
                                                  "RepeatedParamType"
                                                  ((#\nul
                                                    ("Scala"
                                                     "Type"
                                                     #\nul
                                                     ("Scala"
                                                      "InfixType"
                                                      ("Scala"
                                                       "CompoundType"
                                                       ("Scala"
                                                        "AnnotType"
                                                        ("Scala"
                                                         "SimpleType"
                                                         ("Scala" "StableId" (R-Int-))
                                                         #\nul)
                                                        #\nul)
                                                       #\nul
                                                       #\nul)
                                                      #\nul
                                                      #\nul))))
                                                  #\nul)))
                                               ("Scala"
                                                "Type"
                                                #\nul
                                                ("Scala"
                                                 "InfixType"
                                                 ("Scala"
                                                  "CompoundType"
                                                  ("Scala"
                                                   "AnnotType"
                                                   ("Scala"
                                                    "SimpleType"
                                                    ("Scala" "StableId" (R-Double-))
                                                    #\nul)
                                                   #\nul)
                                                  #\nul
                                                  #\nul)
                                                 #\nul
                                                 #\nul)))))))))
                                        (#\nul #\nul))))
                             (#\nul
                              #\nul
                              #\nul
                              #\nul
                              #\nul
                              ("Scala"
                               "PostfixExpression"
                               ("Scala"
                                "InfixExpression"
                                ("Scala"
                                 "PrefixExpression"
                                 #\nul
                                 ("Scala"
                                  "SimpleExpression"
                                  ("Scala"
                                   "idSeqSimpleExpression"
                                   V-println
                                   ("Scala"
                                    "FunctionApplicationPostfix"
                                    ("Scala"
                                     "ArgumentExpression"
                                     ("Scala"
                                      "Exprs"
                                      (("Scala"
                                        "PostfixExpression"
                                        ("Scala"
                                         "InfixExpression"
                                         ("Scala"
                                          "PrefixExpression"
                                          #\nul
                                          ("Scala"
                                           "SimpleExpression"
                                           ("Scala" "idSeqSimpleExpression" V-ary #\nul)
                                           #\nul))
                                         #\nul
                                         #\nul)
                                        #\nul))))
                                    #\nul))
                                  #\nul))
                                #\nul
                                #\nul)
                               #\nul))
                             #\nul))))
                        #\nul
                        #\nul)
                       #\nul)))))
         #\nul
         (#\nul #\nul)))))))
  #\nul)