(begin
  ("Scala"
   "TopStat"
   #\nul
   #\nul
   ("Scala"
    "ObjectTemplateDefinition"
    #\nul
    ("Scala"
     "ObjectDefinition"
     V-Append1
     ("Scala"
      "ClassTemplateOpt"
      #\nul
      ("Scala"
       "TemplateBody"
       (letrec* ((V-e\x60;28*
                   ((val variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (V-Int)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    #\nul))
                 (V-f\x60;28*
                   ((var variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (V-Int)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    #\nul))
                 (V-d\x60;28*
                   ((val variable)
                    (("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala" "SimpleType" ("Scala" "StableId" (V-Int)) #\nul)
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul)))
                    #\nul)))
         #\nul
         (("Scala" "TemplateStatement" #\nul #\nul #\nul)
          ("Scala" "TemplateStatement" #\nul #\nul #\nul)
          ("Scala"
           "TemplateStatement"
           #\nul
           #\nul
           ("Scala"
            "Definition"
            ("Scala"
             "FunctionDefinition"
             ("Scala"
              "FunctionSignature"
              V-main
              #\nul
              ("Scala"
               "ParamClauses"
               (("Scala"
                 "ParamClause"
                 ("Scala"
                  "Params"
                  (("Scala"
                    "Param"
                    #\nul
                    V-args
                    ("Scala"
                     "RepeatedParamType"
                     ("Scala"
                      "Type"
                      #\nul
                      ("Scala"
                       "InfixType"
                       ("Scala"
                        "CompoundType"
                        ("Scala"
                         "AnnotType"
                         ("Scala"
                          "SimpleType"
                          ("Scala" "StableId" (V-Array))
                          (("Scala"
                            "TypeArgs"
                            ("Scala"
                             "Types"
                             (("Scala"
                               "Type"
                               #\nul
                               ("Scala"
                                "InfixType"
                                ("Scala"
                                 "CompoundType"
                                 ("Scala"
                                  "AnnotType"
                                  ("Scala" "SimpleType" ("Scala" "StableId" (V-String)) #\nul)
                                  #\nul)
                                 #\nul
                                 #\nul)
                                #\nul
                                #\nul)))))))
                         #\nul)
                        #\nul
                        #\nul)
                       #\nul
                       #\nul))
                     #\nul)
                    #\nul)))))
               #\nul))
             ("Scala"
              "Type"
              #\nul
              ("Scala"
               "InfixType"
               ("Scala"
                "CompoundType"
                ("Scala"
                 "AnnotType"
                 ("Scala" "SimpleType" ("Scala" "StableId" (V-Unit)) #\nul)
                 #\nul)
                #\nul
                #\nul)
               #\nul
               #\nul))
             ("Scala"
              "PostfixExpression"
              ("Scala"
               "InfixExpression"
               ("Scala"
                "PrefixExpression"
                #\nul
                ("Scala"
                 "BlockExpression"
                 ("Scala"
                  "Block"
                  (letrec* ((V-d\x60;30*
                              ((val variable)
                               (#\nul)
                               ("Scala"
                                "PostfixExpression"
                                ("Scala"
                                 "InfixExpression"
                                 ("Scala"
                                  "PrefixExpression"
                                  #\nul
                                  ("Scala"
                                   "SimpleExpression"
                                   ("Scala"
                                    "literalSimpleExpression"
                                    ("Scala" "booleanLiteral" "false")
                                    #\nul)
                                   #\nul))
                                 #\nul
                                 #\nul)
                                #\nul)))
                            (V-c\x60;30*
                              ((var variable)
                               (#\nul)
                               ("Scala"
                                "PostfixExpression"
                                ("Scala"
                                 "InfixExpression"
                                 ("Scala"
                                  "PrefixExpression"
                                  #\nul
                                  ("Scala"
                                   "SimpleExpression"
                                   ("Scala"
                                    "literalSimpleExpression"
                                    ("Scala" "booleanLiteral" "false")
                                    #\nul)
                                   #\nul))
                                 #\nul
                                 #\nul)
                                #\nul)))
                            (V-f\x60;30*
                              ((val variable)
                               (("Scala"
                                 "Type"
                                 #\nul
                                 ("Scala"
                                  "InfixType"
                                  ("Scala"
                                   "CompoundType"
                                   ("Scala"
                                    "AnnotType"
                                    ("Scala" "SimpleType" ("Scala" "StableId" (V-Int)) #\nul)
                                    #\nul)
                                   #\nul
                                   #\nul)
                                  #\nul
                                  #\nul)))
                               ("Scala"
                                "PostfixExpression"
                                ("Scala"
                                 "InfixExpression"
                                 ("Scala"
                                  "PrefixExpression"
                                  ("Scala" "Keyword" "-")
                                  ("Scala"
                                   "SimpleExpression"
                                   ("Scala" "literalSimpleExpression" 1 #\nul)
                                   #\nul))
                                 #\nul
                                 #\nul)
                                #\nul)))
                            (V-h\x60;30*
                              ((val variable)
                               (("Scala"
                                 "Type"
                                 #\nul
                                 ("Scala"
                                  "InfixType"
                                  ("Scala"
                                   "CompoundType"
                                   ("Scala"
                                    "AnnotType"
                                    ("Scala" "SimpleType" ("Scala" "StableId" (V-Int)) #\nul)
                                    #\nul)
                                   #\nul
                                   #\nul)
                                  #\nul
                                  #\nul)))
                               ("Scala"
                                "PostfixExpression"
                                ("Scala"
                                 "InfixExpression"
                                 ("Scala"
                                  "PrefixExpression"
                                  ("Scala" "Keyword" "-")
                                  ("Scala"
                                   "SimpleExpression"
                                   ("Scala" "literalSimpleExpression" 1 #\nul)
                                   #\nul))
                                 #\nul
                                 #\nul)
                                #\nul)))
                            (V-a\x60;30*
                              ((val variable)
                               (#\nul)
                               (#\nul
                                (("Scala"
                                  "PostfixExpression"
                                  ("Scala"
                                   "InfixExpression"
                                   ("Scala"
                                    "PrefixExpression"
                                    #\nul
                                    ("Scala"
                                     "SimpleExpression"
                                     ("Scala"
                                      "TupleExpression"
                                      ("Scala"
                                       "Exprs"
                                       (("Scala"
                                         "AnonymousFunction"
                                         (lambda (V-f\x60;31\x60;32*)
                                           (#\nul)
                                           ("Scala"
                                            "PostfixExpression"
                                            ("Scala"
                                             "InfixExpression"
                                             ("Scala"
                                              "PrefixExpression"
                                              #\nul
                                              ("Scala"
                                               "BlockExpression"
                                               ("Scala"
                                                "Block"
                                                (letrec* ((V-d\x60;31\x60;34*
                                                            ((val variable)
                                                             (#\nul)
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "literalSimpleExpression"
                                                                  3
                                                                  #\nul)
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul))))
                                                  (("Scala" "BlockStat" #\nul #\nul #\nul)
                                                   ("Scala"
                                                    "IfStatement"
                                                    ("Scala"
                                                     "PostfixExpression"
                                                     ("Scala"
                                                      "InfixExpression"
                                                      ("Scala"
                                                       "PrefixExpression"
                                                       #\nul
                                                       ("Scala"
                                                        "SimpleExpression"
                                                        ("Scala"
                                                         "idSeqSimpleExpression"
                                                         V-f\x60;31\x60;32*
                                                         #\nul)
                                                        #\nul))
                                                      #\nul
                                                      #\nul)
                                                     #\nul)
                                                    ("Scala"
                                                     "PostfixExpression"
                                                     ("Scala"
                                                      "InfixExpression"
                                                      ("Scala"
                                                       "PrefixExpression"
                                                       #\nul
                                                       ("Scala"
                                                        "SimpleExpression"
                                                        ("Scala"
                                                         "idSeqSimpleExpression"
                                                         ("Scala"
                                                          "PostfixExpression"
                                                          ("Scala"
                                                           "InfixExpression"
                                                           ("Scala"
                                                            "PrefixExpression"
                                                            #\nul
                                                            ("Scala"
                                                             "SimpleExpression"
                                                             ("Scala"
                                                              "idSeqSimpleExpression"
                                                              V-d\x60;30*
                                                              #\nul)
                                                             #\nul))
                                                           #\nul
                                                           #\nul)
                                                          #\nul)
                                                         #\nul)
                                                        #\nul))
                                                      #\nul
                                                      #\nul)
                                                     #\nul)
                                                    ("Scala"
                                                     "PostfixExpression"
                                                     ("Scala"
                                                      "InfixExpression"
                                                      ("Scala"
                                                       "PrefixExpression"
                                                       #\nul
                                                       ("Scala"
                                                        "SimpleExpression"
                                                        ("Scala"
                                                         "idSeqSimpleExpression"
                                                         V-d\x60;31\x60;34*
                                                         #\nul)
                                                        #\nul))
                                                      #\nul
                                                      #\nul)
                                                     #\nul)))
                                                  #\nul))))
                                             #\nul
                                             #\nul)
                                            #\nul)))))
                                      ("Scala"
                                       "FunctionApplicationPostfix"
                                       ("Scala"
                                        "ArgumentExpression"
                                        ("Scala"
                                         "Exprs"
                                         (("Scala"
                                           "PostfixExpression"
                                           ("Scala"
                                            "InfixExpression"
                                            ("Scala"
                                             "PrefixExpression"
                                             #\nul
                                             ("Scala"
                                              "SimpleExpression"
                                              ("Scala"
                                               "idSeqSimpleExpression"
                                               ("Scala"
                                                "PostfixExpression"
                                                ("Scala"
                                                 "InfixExpression"
                                                 ("Scala"
                                                  "PrefixExpression"
                                                  #\nul
                                                  ("Scala"
                                                   "SimpleExpression"
                                                   ("Scala"
                                                    "idSeqSimpleExpression"
                                                    V-d\x60;30*
                                                    #\nul)
                                                   #\nul))
                                                 #\nul
                                                 #\nul)
                                                #\nul)
                                               #\nul)
                                              #\nul))
                                            #\nul
                                            #\nul)
                                           #\nul))))
                                       #\nul))
                                     #\nul))
                                   #\nul
                                   #\nul)
                                  #\nul))
                                #\nul)))
                            (V-g\x60;30*
                              ((val variable)
                               (#\nul)
                               ("Scala"
                                "PostfixExpression"
                                ("Scala"
                                 "InfixExpression"
                                 ("Scala"
                                  "PrefixExpression"
                                  #\nul
                                  ("Scala"
                                   "SimpleExpression"
                                   ("Scala" "idSeqSimpleExpression" V-f\x60;30* #\nul)
                                   #\nul))
                                 #\nul
                                 #\nul)
                                #\nul)))
                            (V-z\x60;30*
                              ((var variable)
                               (("Scala"
                                 "Type"
                                 #\nul
                                 ("Scala"
                                  "InfixType"
                                  ("Scala"
                                   "CompoundType"
                                   ("Scala"
                                    "AnnotType"
                                    ("Scala" "SimpleType" ("Scala" "StableId" (V-Int)) #\nul)
                                    #\nul)
                                   #\nul
                                   #\nul)
                                  #\nul
                                  #\nul)))
                               ("Scala" "Keyword" "_")))
                            (V-y\x60;30*
                              ((var variable)
                               (("Scala"
                                 "Type"
                                 #\nul
                                 ("Scala"
                                  "InfixType"
                                  ("Scala"
                                   "CompoundType"
                                   ("Scala"
                                    "AnnotType"
                                    ("Scala" "SimpleType" ("Scala" "StableId" (V-Int)) #\nul)
                                    #\nul)
                                   #\nul
                                   #\nul)
                                  #\nul
                                  #\nul)))
                               ("Scala" "Keyword" "_"))))
                    (("Scala" "BlockStat" #\nul #\nul #\nul)
                     ("Scala" "BlockStat" #\nul #\nul #\nul)
                     ("Scala" "BlockStat" #\nul #\nul #\nul)
                     ("Scala" "BlockStat" #\nul #\nul #\nul)
                     ("Scala"
                      "PostfixExpression"
                      ("Scala"
                       "InfixExpression"
                       ("Scala"
                        "PrefixExpression"
                        #\nul
                        ("Scala"
                         "SimpleExpression"
                         ("Scala"
                          "idSeqSimpleExpression"
                          V-println
                          ("Scala"
                           "FunctionApplicationPostfix"
                           ("Scala"
                            "ArgumentExpression"
                            ("Scala"
                             "Exprs"
                             (("Scala"
                               "PostfixExpression"
                               ("Scala"
                                "InfixExpression"
                                ("Scala"
                                 "PrefixExpression"
                                 #\nul
                                 ("Scala"
                                  "SimpleExpression"
                                  ("Scala" "idSeqSimpleExpression" V-$body #\nul)
                                  #\nul))
                                #\nul
                                #\nul)
                               #\nul))))
                           #\nul))
                         #\nul))
                       #\nul
                       #\nul)
                      #\nul)
                     ("Scala" "BlockStat" #\nul #\nul #\nul)
                     ("Scala" "BlockStat" #\nul #\nul #\nul))
                    #\nul))))
               #\nul
               #\nul)
              #\nul))))
          ("Scala" "TemplateStatement" #\nul #\nul #\nul)
          #\nul)))))))
  #\nul)