(begin
  ("Scala"
   "TopStat"
   #\nul
   #\nul
   ("Scala"
    "ObjectTemplateDefinition"
    #\nul
    ("Scala"
     "ObjectDefinition"
     V-Append1
     ("Scala"
      "ClassTemplateOpt"
      #\nul
      ("Scala"
       "TemplateBody"
       (letrec* ((R-main-\x60;28*
                   ((lambda ()
                      (function FunctionDefinition)
                      (#\nul #\nul)
                      ("Scala"
                       "FunctionSignature"
                       R-main-\x60;28*
                       #\nul
                       ("Scala"
                        "ParamClauses"
                        (("Scala"
                          "ParamClause"
                          ("Scala"
                           "Params"
                           (("Scala"
                             "Param"
                             #\nul
                             R-args-
                             ("Scala"
                              "RepeatedParamType"
                              ("Scala"
                               "Type"
                               #\nul
                               ("Scala"
                                "InfixType"
                                ("Scala"
                                 "CompoundType"
                                 ("Scala"
                                  "AnnotType"
                                  ("Scala"
                                   "SimpleType"
                                   ("Scala" "StableId" (R-Array-))
                                   (("Scala"
                                     "TypeArgs"
                                     ("Scala"
                                      "Types"
                                      (("Scala"
                                        "Type"
                                        #\nul
                                        ("Scala"
                                         "InfixType"
                                         ("Scala"
                                          "CompoundType"
                                          ("Scala"
                                           "AnnotType"
                                           ("Scala"
                                            "SimpleType"
                                            ("Scala" "StableId" (R-String-))
                                            #\nul)
                                           #\nul)
                                          #\nul
                                          #\nul)
                                         #\nul
                                         #\nul)))))))
                                  #\nul)
                                 #\nul
                                 #\nul)
                                #\nul
                                #\nul))
                              #\nul)
                             #\nul)))))
                        #\nul))
                      ("Scala"
                       "Type"
                       #\nul
                       ("Scala"
                        "InfixType"
                        ("Scala"
                         "CompoundType"
                         ("Scala"
                          "AnnotType"
                          ("Scala" "SimpleType" ("Scala" "StableId" (R-Unit-)) #\nul)
                          #\nul)
                         #\nul
                         #\nul)
                        #\nul
                        #\nul))
                      ("Scala"
                       "PostfixExpression"
                       ("Scala"
                        "InfixExpression"
                        ("Scala"
                         "PrefixExpression"
                         #\nul
                         ("Scala"
                          "BlockExpression"
                          ("Scala"
                           "Block"
                           (letrec* ((V-a\x60;31*
                                       ((val variable)
                                        (#\nul)
                                        ("Scala"
                                         "PostfixExpression"
                                         ("Scala"
                                          "InfixExpression"
                                          ("Scala"
                                           "PrefixExpression"
                                           #\nul
                                           ("Scala"
                                            "SimpleExpression"
                                            ("Scala"
                                             "literalSimpleExpression"
                                             ("Scala" "booleanLiteral" "false")
                                             #\nul)
                                            #\nul))
                                          #\nul
                                          #\nul)
                                         #\nul)
                                        (#\nul #\nul)))
                                     (V-f\x60;31*
                                       ((var variable)
                                        (#\nul)
                                        ("Scala"
                                         "PostfixExpression"
                                         ("Scala"
                                          "InfixExpression"
                                          ("Scala"
                                           "PrefixExpression"
                                           ("Scala" "Keyword" "-")
                                           ("Scala"
                                            "SimpleExpression"
                                            ("Scala" "literalSimpleExpression" 1 #\nul)
                                            #\nul))
                                          #\nul
                                          #\nul)
                                         #\nul)
                                        (#\nul #\nul)))
                                     (V-b\x60;31*
                                       ((val variable)
                                        (#\nul)
                                        (#\nul
                                         (("Scala"
                                           "PostfixExpression"
                                           ("Scala"
                                            "InfixExpression"
                                            ("Scala"
                                             "PrefixExpression"
                                             #\nul
                                             ("Scala"
                                              "SimpleExpression"
                                              ("Scala"
                                               "TupleExpression"
                                               ("Scala"
                                                "Exprs"
                                                (("Scala"
                                                  "AnonymousFunction"
                                                  (lambda (V-f\x60;32\x60;33*)
                                                    (#\nul)
                                                    ("Scala"
                                                     "PostfixExpression"
                                                     ("Scala"
                                                      "InfixExpression"
                                                      ("Scala"
                                                       "PrefixExpression"
                                                       #\nul
                                                       ("Scala"
                                                        "BlockExpression"
                                                        ("Scala"
                                                         "Block"
                                                         (let ()
                                                           (("Scala"
                                                             "IfStatement"
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "idSeqSimpleExpression"
                                                                  V-f\x60;32\x60;33*
                                                                  #\nul)
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul)
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "idSeqSimpleExpression"
                                                                  V-f\x60;32\x60;33*
                                                                  #\nul)
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul)
                                                             ("Scala"
                                                              "PostfixExpression"
                                                              ("Scala"
                                                               "InfixExpression"
                                                               ("Scala"
                                                                "PrefixExpression"
                                                                #\nul
                                                                ("Scala"
                                                                 "SimpleExpression"
                                                                 ("Scala"
                                                                  "idSeqSimpleExpression"
                                                                  V-f\x60;31*
                                                                  #\nul)
                                                                 #\nul))
                                                               #\nul
                                                               #\nul)
                                                              #\nul)))
                                                           #\nul))))
                                                      #\nul
                                                      #\nul)
                                                     #\nul)))))
                                               ("Scala"
                                                "FunctionApplicationPostfix"
                                                ("Scala"
                                                 "ArgumentExpression"
                                                 ("Scala"
                                                  "Exprs"
                                                  (("Scala"
                                                    "PostfixExpression"
                                                    ("Scala"
                                                     "InfixExpression"
                                                     ("Scala"
                                                      "PrefixExpression"
                                                      #\nul
                                                      ("Scala"
                                                       "SimpleExpression"
                                                       ("Scala"
                                                        "idSeqSimpleExpression"
                                                        ("Scala"
                                                         "PostfixExpression"
                                                         ("Scala"
                                                          "InfixExpression"
                                                          ("Scala"
                                                           "PrefixExpression"
                                                           #\nul
                                                           ("Scala"
                                                            "SimpleExpression"
                                                            ("Scala"
                                                             "literalSimpleExpression"
                                                             ("Scala" "booleanLiteral" "false")
                                                             #\nul)
                                                            #\nul))
                                                          #\nul
                                                          #\nul)
                                                         #\nul)
                                                        #\nul)
                                                       #\nul))
                                                     #\nul
                                                     #\nul)
                                                    #\nul))))
                                                #\nul))
                                              #\nul))
                                            #\nul
                                            #\nul)
                                           #\nul))
                                         #\nul)
                                        (#\nul #\nul))))
                             (#\nul
                              #\nul
                              #\nul
                              ("Scala"
                               "PostfixExpression"
                               ("Scala"
                                "InfixExpression"
                                ("Scala"
                                 "PrefixExpression"
                                 #\nul
                                 ("Scala"
                                  "SimpleExpression"
                                  ("Scala"
                                   "idSeqSimpleExpression"
                                   V-println
                                   ("Scala"
                                    "FunctionApplicationPostfix"
                                    ("Scala"
                                     "ArgumentExpression"
                                     ("Scala"
                                      "Exprs"
                                      (("Scala"
                                        "PostfixExpression"
                                        ("Scala"
                                         "InfixExpression"
                                         ("Scala"
                                          "PrefixExpression"
                                          #\nul
                                          ("Scala"
                                           "SimpleExpression"
                                           ("Scala" "idSeqSimpleExpression" V-b\x60;31* #\nul)
                                           #\nul))
                                         #\nul
                                         #\nul)
                                        #\nul))))
                                    #\nul))
                                  #\nul))
                                #\nul
                                #\nul)
                               #\nul))
                             #\nul))))
                        #\nul
                        #\nul)
                       #\nul)))))
         #\nul
         (#\nul #\nul)))))))
  #\nul)