(begin
  #\nul
  (begin)
  ("Scala"
   "TopStat"
   #\nul
   #\nul
   ("Scala"
    "ObjectTemplateDefinition"
    #\nul
    ("Scala"
     "ObjectDefinition"
     V-Rec_Func
     ("Scala"
      "ClassTemplateOpt"
      #\nul
      ("Scala"
       "TemplateBody"
       (letrec* ((R-main-\x60;28*
                   ((lambda ()
                      (function FunctionDefinition)
                      (#\nul #\nul)
                      ("Scala"
                       "FunctionSignature"
                       R-main-\x60;28*
                       #\nul
                       ("Scala"
                        "ParamClauses"
                        (("Scala"
                          "ParamClause"
                          ("Scala"
                           "Params"
                           (("Scala"
                             "Param"
                             #\nul
                             R-args-
                             ("Scala"
                              "RepeatedParamType"
                              ("Scala"
                               "Type"
                               #\nul
                               ("Scala"
                                "InfixType"
                                ("Scala"
                                 "CompoundType"
                                 ("Scala"
                                  "AnnotType"
                                  ("Scala"
                                   "SimpleType"
                                   ("Scala" "StableId" (R-Array-))
                                   (("Scala"
                                     "TypeArgs"
                                     ("Scala"
                                      "Types"
                                      (("Scala"
                                        "Type"
                                        #\nul
                                        ("Scala"
                                         "InfixType"
                                         ("Scala"
                                          "CompoundType"
                                          ("Scala"
                                           "AnnotType"
                                           ("Scala"
                                            "SimpleType"
                                            ("Scala" "StableId" (R-String-))
                                            #\nul)
                                           #\nul)
                                          #\nul
                                          #\nul)
                                         #\nul
                                         #\nul)))))))
                                  #\nul)
                                 #\nul
                                 #\nul)
                                #\nul
                                #\nul))
                              #\nul)
                             #\nul)))))
                        #\nul))
                      ("Scala"
                       "Type"
                       #\nul
                       ("Scala"
                        "InfixType"
                        ("Scala"
                         "CompoundType"
                         ("Scala"
                          "AnnotType"
                          ("Scala" "SimpleType" ("Scala" "StableId" (R-Unit-)) #\nul)
                          #\nul)
                         #\nul
                         #\nul)
                        #\nul
                        #\nul))
                      ("Scala"
                       "PostfixExpression"
                       ("Scala"
                        "InfixExpression"
                        ("Scala"
                         "PrefixExpression"
                         #\nul
                         ("Scala"
                          "BlockExpression"
                          ("Scala"
                           "Block"
                           (letrec* ((V-tmp\x60;31*
                                       ((val variable)
                                        (#\nul)
                                        ("Scala"
                                         "PostfixExpression"
                                         ("Scala"
                                          "InfixExpression"
                                          ("Scala"
                                           "PrefixExpression"
                                           #\nul
                                           ("Scala"
                                            "SimpleExpression"
                                            ("Scala" "literalSimpleExpression" 100 #\nul)
                                            #\nul))
                                          #\nul
                                          #\nul)
                                         #\nul)
                                        (#\nul #\nul))))
                             (#\nul
                              ("Scala"
                               "PostfixExpression"
                               ("Scala"
                                "InfixExpression"
                                ("Scala"
                                 "PrefixExpression"
                                 #\nul
                                 ("Scala"
                                  "SimpleExpression"
                                  ("Scala" "idSeqSimpleExpression" V-Abs #\nul)
                                  #\nul))
                                #\nul
                                #\nul)
                               V-tmp\x60;31*))
                             #\nul))))
                        #\nul
                        #\nul)
                       #\nul)))))
         #\nul
         (#\nul #\nul)))))))
  #\nul)