(begin
  ("Scala"
   "TopStat"
   #\nul
   #\nul
   ("Scala"
    "ObjectTemplateDefinition"
    #\nul
    ("Scala"
     "ObjectDefinition"
     V-Append1
     ("Scala"
      "ClassTemplateOpt"
      #\nul
      ("Scala"
       "TemplateBody"
       (letrec* ((R-main-\x60;28*
                   ((lambda ()
                      (function FunctionDefinition)
                      (#\nul #\nul)
                      ("Scala"
                       "FunctionSignature"
                       R-main-\x60;28*
                       #\nul
                       ("Scala"
                        "ParamClauses"
                        (("Scala"
                          "ParamClause"
                          ("Scala"
                           "Params"
                           (("Scala"
                             "Param"
                             #\nul
                             R-args-
                             ("Scala"
                              "RepeatedParamType"
                              ("Scala"
                               "Type"
                               #\nul
                               ("Scala"
                                "InfixType"
                                ("Scala"
                                 "CompoundType"
                                 ("Scala"
                                  "AnnotType"
                                  ("Scala"
                                   "SimpleType"
                                   ("Scala" "StableId" (R-Array-))
                                   (("Scala"
                                     "TypeArgs"
                                     ("Scala"
                                      "Types"
                                      (("Scala"
                                        "Type"
                                        #\nul
                                        ("Scala"
                                         "InfixType"
                                         ("Scala"
                                          "CompoundType"
                                          ("Scala"
                                           "AnnotType"
                                           ("Scala"
                                            "SimpleType"
                                            ("Scala" "StableId" (R-String-))
                                            #\nul)
                                           #\nul)
                                          #\nul
                                          #\nul)
                                         #\nul
                                         #\nul)))))))
                                  #\nul)
                                 #\nul
                                 #\nul)
                                #\nul
                                #\nul))
                              #\nul)
                             #\nul)))))
                        #\nul))
                      ("Scala"
                       "Type"
                       #\nul
                       ("Scala"
                        "InfixType"
                        ("Scala"
                         "CompoundType"
                         ("Scala"
                          "AnnotType"
                          ("Scala" "SimpleType" ("Scala" "StableId" (R-Unit-)) #\nul)
                          #\nul)
                         #\nul
                         #\nul)
                        #\nul
                        #\nul))
                      ("Scala"
                       "PostfixExpression"
                       ("Scala"
                        "InfixExpression"
                        ("Scala"
                         "PrefixExpression"
                         #\nul
                         ("Scala"
                          "BlockExpression"
                          ("Scala"
                           "Block"
                           (letrec* ((V-a\x60;31*
                                       ((val variable)
                                        (#\nul)
                                        ("Scala"
                                         "PostfixExpression"
                                         ("Scala"
                                          "InfixExpression"
                                          ("Scala"
                                           "PrefixExpression"
                                           #\nul
                                           ("Scala"
                                            "SimpleExpression"
                                            ("Scala" "literalSimpleExpression" 3 #\nul)
                                            #\nul))
                                          #\nul
                                          #\nul)
                                         #\nul)
                                        (#\nul #\nul)))
                                     (V-t1\x60;31*
                                       ((type TypeDefinition)
                                        (#\nul)
                                        ("Scala"
                                         "Type"
                                         #\nul
                                         ("Scala"
                                          "InfixType"
                                          ("Scala"
                                           "CompoundType"
                                           ("Scala"
                                            "AnnotType"
                                            ("Scala"
                                             "SimpleType"
                                             ("Scala" "StableId" (R-Int-))
                                             #\nul)
                                            #\nul)
                                           #\nul
                                           #\nul)
                                          #\nul
                                          #\nul))
                                        (#\nul #\nul))))
                             (#\nul
                              #\nul
                              ("Scala"
                               "PostfixExpression"
                               ("Scala"
                                "InfixExpression"
                                ("Scala"
                                 "PrefixExpression"
                                 #\nul
                                 ("Scala"
                                  "SimpleExpression"
                                  ("Scala"
                                   "idSeqSimpleExpression"
                                   V-println
                                   ("Scala"
                                    "FunctionApplicationPostfix"
                                    ("Scala"
                                     "ArgumentExpression"
                                     ("Scala"
                                      "Exprs"
                                      ((#\nul
                                        (("Scala"
                                          "PostfixExpression"
                                          ("Scala"
                                           "InfixExpression"
                                           ("Scala"
                                            "PrefixExpression"
                                            #\nul
                                            ("Scala"
                                             "SimpleExpression"
                                             ("Scala"
                                              "TupleExpression"
                                              ("Scala"
                                               "Exprs"
                                               (("Scala"
                                                 "AnonymousFunction"
                                                 (lambda (V-x\x60;34* V-y\x60;34*)
                                                   (("Scala"
                                                     "Type"
                                                     #\nul
                                                     ("Scala"
                                                      "InfixType"
                                                      ("Scala"
                                                       "CompoundType"
                                                       ("Scala"
                                                        "AnnotType"
                                                        ("Scala"
                                                         "SimpleType"
                                                         ("Scala" "StableId" (R-Int-))
                                                         #\nul)
                                                        #\nul)
                                                       #\nul
                                                       #\nul)
                                                      #\nul
                                                      #\nul))
                                                    ("Scala"
                                                     "Type"
                                                     #\nul
                                                     ("Scala"
                                                      "InfixType"
                                                      ("Scala"
                                                       "CompoundType"
                                                       ("Scala"
                                                        "AnnotType"
                                                        ("Scala"
                                                         "SimpleType"
                                                         ("Scala" "StableId" (V-t1\x60;31*))
                                                         #\nul)
                                                        #\nul)
                                                       #\nul
                                                       #\nul)
                                                      #\nul
                                                      #\nul)))
                                                   ("Scala"
                                                    "PostfixExpression"
                                                    ("Scala"
                                                     "InfixExpression"
                                                     ("Scala"
                                                      "PrefixExpression"
                                                      #\nul
                                                      ("Scala"
                                                       "SimpleExpression"
                                                       ("Scala"
                                                        "idSeqSimpleExpression"
                                                        ("Scala"
                                                         "PostfixExpression"
                                                         ("Scala"
                                                          "InfixExpression"
                                                          ("Scala"
                                                           "PrefixExpression"
                                                           #\nul
                                                           ("Scala"
                                                            "SimpleExpression"
                                                            ("Scala"
                                                             "idSeqSimpleExpression"
                                                             V-x\x60;34*
                                                             #\nul)
                                                            #\nul))
                                                          (V-*)
                                                          (("Scala"
                                                            "InfixExpression"
                                                            ("Scala"
                                                             "PrefixExpression"
                                                             #\nul
                                                             ("Scala"
                                                              "SimpleExpression"
                                                              ("Scala"
                                                               "idSeqSimpleExpression"
                                                               V-y\x60;34*
                                                               #\nul)
                                                              #\nul))
                                                            #\nul
                                                            #\nul)))
                                                         #\nul)
                                                        #\nul)
                                                       #\nul))
                                                     #\nul
                                                     #\nul)
                                                    #\nul)))))
                                              ("Scala"
                                               "FunctionApplicationPostfix"
                                               ("Scala"
                                                "ArgumentExpression"
                                                ("Scala"
                                                 "Exprs"
                                                 (("Scala"
                                                   "PostfixExpression"
                                                   ("Scala"
                                                    "InfixExpression"
                                                    ("Scala"
                                                     "PrefixExpression"
                                                     #\nul
                                                     ("Scala"
                                                      "SimpleExpression"
                                                      ("Scala"
                                                       "idSeqSimpleExpression"
                                                       ("Scala"
                                                        "PostfixExpression"
                                                        ("Scala"
                                                         "InfixExpression"
                                                         ("Scala"
                                                          "PrefixExpression"
                                                          #\nul
                                                          ("Scala"
                                                           "SimpleExpression"
                                                           ("Scala"
                                                            "literalSimpleExpression"
                                                            3
                                                            #\nul)
                                                           #\nul))
                                                         (V-*)
                                                         (("Scala"
                                                           "InfixExpression"
                                                           ("Scala"
                                                            "PrefixExpression"
                                                            #\nul
                                                            ("Scala"
                                                             "SimpleExpression"
                                                             ("Scala"
                                                              "literalSimpleExpression"
                                                              5
                                                              #\nul)
                                                             #\nul))
                                                           #\nul
                                                           #\nul)))
                                                        #\nul)
                                                       #\nul)
                                                      #\nul))
                                                    #\nul
                                                    #\nul)
                                                   #\nul)
                                                  ("Scala"
                                                   "PostfixExpression"
                                                   ("Scala"
                                                    "InfixExpression"
                                                    ("Scala"
                                                     "PrefixExpression"
                                                     #\nul
                                                     ("Scala"
                                                      "SimpleExpression"
                                                      ("Scala"
                                                       "idSeqSimpleExpression"
                                                       ("Scala"
                                                        "PostfixExpression"
                                                        ("Scala"
                                                         "InfixExpression"
                                                         ("Scala"
                                                          "PrefixExpression"
                                                          #\nul
                                                          ("Scala"
                                                           "SimpleExpression"
                                                           ("Scala"
                                                            "literalSimpleExpression"
                                                            10
                                                            #\nul)
                                                           #\nul))
                                                         #\nul
                                                         #\nul)
                                                        #\nul)
                                                       #\nul)
                                                      #\nul))
                                                    #\nul
                                                    #\nul)
                                                   #\nul))))
                                               #\nul))
                                             #\nul))
                                           #\nul
                                           #\nul)
                                          #\nul))
                                        #\nul))))
                                    #\nul))
                                  #\nul))
                                #\nul
                                #\nul)
                               #\nul))
                             #\nul))))
                        #\nul
                        #\nul)
                       #\nul)))))
         #\nul
         (#\nul #\nul)))))))
  #\nul)